### ISSUE TITLE
Efficiency: no recalculation of original latents needed

### ISSUE THREAD

**Issue by NotNANtoN** [hila-chefer/TargetCLIP#5]
https://github.com/hila-chefer/TargetCLIP/blob/b5dd2a492bf436fa26cfa4c02021a957b6a2a5ec/optimization/find_dirs.py#L142-L144

In these lines the latents are recalculated in the nested loop in every inner loop. The latents themselves stay constant though, so it can be done once outside of these loops. Only the augmented latents (latents + direction) need to be recalculated here.

**Comment by hila-chefer** [comment]
Hi @NotNANtoN, thanks for your interest in our work!
you are of course correct, it can be done for efficiency, but the contribution of this fix to the overall runtime is relatively small. Optimizing a single direction takes around 10 minutes either way :)

**Comment by hila-chefer** [comment]
@NotNANtoN closing this due to duplication, please reopen if necessary :)
