### ISSUE TITLE
amazing work

### ISSUE THREAD

**Issue by molo32** [hila-chefer/TargetCLIP#7]
amazing work

let me congratulate you on this incredible job, unfortunately I don't have the computing power to train targets, I'd like you to add some celebrity targets like megan fox and emilia clacke, and other celebrities.
and add new ones, for people who don't have a gpu, every week if they have free time and no work is busy.

**Comment by hila-chefer** [comment]
Hi @molo32, thanks for your interest in our work :)
Every once in a while, I update our notebook with additional directions, so I'll keep your requests in mind :)

**Comment by hila-chefer** [comment]
@molo32 added some new celebrity directions- check it out :)
